services:
  - type: web
    name: techpro-booking-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DATABASE_URL
        fromDatabase:
          name: techpro_db
          property: connectionString